// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAmbisonicsDecodeEffectParams(
    public val `$mem`: MemorySegment,
) {
    public var order: IPLint32
        get() = IPLAmbisonicsDecodeEffectParams.orderHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAmbisonicsDecodeEffectParams.orderHandle.set(this.`$mem`, 0L, value)
        }

    public var hrtf: IPLHRTF
        get() = IPLAmbisonicsDecodeEffectParams.hrtfHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            IPLAmbisonicsDecodeEffectParams.hrtfHandle.set(this.`$mem`, 0L, value)
        }

    public var orientation: IPLCoordinateSpace3
        get() =
            IPLCoordinateSpace3(
                IPLAmbisonicsDecodeEffectParams.orientationHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.orientation.`$mem`, 0L,
                IPLCoordinateSpace3.layout.byteSize()
            )
        }

    public var binaural: IPLbool
        get() = IPLbool.fromInt(
            IPLAmbisonicsDecodeEffectParams.binauralHandle.get(this.`$mem`, 0L) as
                    Int
        )
        set(`value`) {
            IPLAmbisonicsDecodeEffectParams.binauralHandle.set(this.`$mem`, 0L, value.value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAmbisonicsDecodeEffectParams.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("order"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("hrtf"),
            IPLCoordinateSpace3.layout.withName("orientation"),
            ValueLayout.JAVA_INT.withName("binaural"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("IPLAmbisonicsDecodeEffectParams")

        @JvmField
        public val orderHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("order"))

        @JvmField
        public val hrtfHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hrtf"))

        @JvmField
        public val orientationHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("orientation"))

        @JvmField
        public val binauralHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("binaural"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAmbisonicsDecodeEffectParams =
            IPLAmbisonicsDecodeEffectParams(alloc.allocate(IPLAmbisonicsDecodeEffectParams.layout))
    }
}
