// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAudioSettings(
    public val `$mem`: MemorySegment,
) {
    public var samplingRate: IPLint32
        get() = IPLAudioSettings.samplingRateHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAudioSettings.samplingRateHandle.set(this.`$mem`, 0L, value)
        }

    public var frameSize: IPLint32
        get() = IPLAudioSettings.frameSizeHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAudioSettings.frameSizeHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAudioSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("samplingRate"),
            ValueLayout.JAVA_INT.withName("frameSize"),
        ).withName("IPLAudioSettings")

        @JvmField
        public val samplingRateHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("samplingRate"))

        @JvmField
        public val frameSizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("frameSize"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAudioSettings =
            IPLAudioSettings(alloc.allocate(IPLAudioSettings.layout))
    }
}
