// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLAirAbsorptionModelType(
    public val `value`: Int,
) {
    IPL_AIRABSORPTIONTYPE_DEFAULT(0x00000000),
    IPL_AIRABSORPTIONTYPE_EXPONENTIAL(0x00000001),
    IPL_AIRABSORPTIONTYPE_CALLBACK(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLAirAbsorptionModelType::class.java,
            "fromInt",
            MethodType.methodType(IPLAirAbsorptionModelType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLAirAbsorptionModelType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLAirAbsorptionModelType = when (value) {
            0x00000000 -> IPL_AIRABSORPTIONTYPE_DEFAULT
            0x00000001 -> IPL_AIRABSORPTIONTYPE_EXPONENTIAL
            0x00000002 -> IPL_AIRABSORPTIONTYPE_CALLBACK
            else -> error("enum not found")
        }
    }
}
