// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAmbisonicsBinauralEffectSettings(
    public val `$mem`: MemorySegment,
) {
    public var hrtf: IPLHRTF
        get() = IPLAmbisonicsBinauralEffectSettings.hrtfHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            IPLAmbisonicsBinauralEffectSettings.hrtfHandle.set(this.`$mem`, 0L, value)
        }

    public var maxOrder: IPLint32
        get() = IPLAmbisonicsBinauralEffectSettings.maxOrderHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAmbisonicsBinauralEffectSettings.maxOrderHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAmbisonicsBinauralEffectSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("hrtf"),
            ValueLayout.JAVA_INT.withName("maxOrder"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("IPLAmbisonicsBinauralEffectSettings")

        @JvmField
        public val hrtfHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hrtf"))

        @JvmField
        public val maxOrderHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("maxOrder"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAmbisonicsBinauralEffectSettings =
            IPLAmbisonicsBinauralEffectSettings(alloc.allocate(IPLAmbisonicsBinauralEffectSettings.layout))
    }
}
