// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLAmbisonicsType(
    public val `value`: Int,
) {
    IPL_AMBISONICSTYPE_N3D(0x00000000),
    IPL_AMBISONICSTYPE_SN3D(0x00000001),
    IPL_AMBISONICSTYPE_FUMA(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLAmbisonicsType::class.java,
            "fromInt",
            MethodType.methodType(IPLAmbisonicsType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLAmbisonicsType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLAmbisonicsType = when (value) {
            0x00000000 -> IPL_AMBISONICSTYPE_N3D
            0x00000001 -> IPL_AMBISONICSTYPE_SN3D
            0x00000002 -> IPL_AMBISONICSTYPE_FUMA
            else -> error("enum not found")
        }
    }
}
