// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAmbisonicsDecodeEffectSettings(
    public val `$mem`: MemorySegment,
) {
    public var speakerLayout: IPLSpeakerLayout
        get() =
            IPLSpeakerLayout(
                IPLAmbisonicsDecodeEffectSettings.speakerLayoutHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.speakerLayout.`$mem`, 0L,
                IPLSpeakerLayout.layout.byteSize()
            )
        }

    public var hrtf: IPLHRTF
        get() = IPLAmbisonicsDecodeEffectSettings.hrtfHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            IPLAmbisonicsDecodeEffectSettings.hrtfHandle.set(this.`$mem`, 0L, value)
        }

    public var maxOrder: IPLint32
        get() = IPLAmbisonicsDecodeEffectSettings.maxOrderHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAmbisonicsDecodeEffectSettings.maxOrderHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAmbisonicsDecodeEffectSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            IPLSpeakerLayout.layout.withName("speakerLayout"),
            `$RuntimeHelper`.POINTER.withName("hrtf"),
            ValueLayout.JAVA_INT.withName("maxOrder"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("IPLAmbisonicsDecodeEffectSettings")

        @JvmField
        public val speakerLayoutHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("speakerLayout"))

        @JvmField
        public val hrtfHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hrtf"))

        @JvmField
        public val maxOrderHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("maxOrder"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAmbisonicsDecodeEffectSettings =
            IPLAmbisonicsDecodeEffectSettings(alloc.allocate(IPLAmbisonicsDecodeEffectSettings.layout))
    }
}
