// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAmbisonicsEncodeEffectParams(
    public val `$mem`: MemorySegment,
) {
    public var direction: IPLVector3
        get() = IPLVector3(
            IPLAmbisonicsEncodeEffectParams.directionHandle.invokeExact(this.`$mem`, 0L)
                    as MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.direction.`$mem`, 0L, IPLVector3.layout.byteSize())
        }

    public var order: IPLint32
        get() = IPLAmbisonicsEncodeEffectParams.orderHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAmbisonicsEncodeEffectParams.orderHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAmbisonicsEncodeEffectParams.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            IPLVector3.layout.withName("direction"),
            ValueLayout.JAVA_INT.withName("order"),
        ).withName("IPLAmbisonicsEncodeEffectParams")

        @JvmField
        public val directionHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("direction"))

        @JvmField
        public val orderHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("order"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAmbisonicsEncodeEffectParams =
            IPLAmbisonicsEncodeEffectParams(alloc.allocate(IPLAmbisonicsEncodeEffectParams.layout))
    }
}
