// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLAmbisonicsRotationEffectParams(
    public val `$mem`: MemorySegment,
) {
    public var orientation: IPLCoordinateSpace3
        get() =
            IPLCoordinateSpace3(
                IPLAmbisonicsRotationEffectParams.orientationHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.orientation.`$mem`, 0L,
                IPLCoordinateSpace3.layout.byteSize()
            )
        }

    public var order: IPLint32
        get() = IPLAmbisonicsRotationEffectParams.orderHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            IPLAmbisonicsRotationEffectParams.orderHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLAmbisonicsRotationEffectParams.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            IPLCoordinateSpace3.layout.withName("orientation"),
            ValueLayout.JAVA_INT.withName("order"),
        ).withName("IPLAmbisonicsRotationEffectParams")

        @JvmField
        public val orientationHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("orientation"))

        @JvmField
        public val orderHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("order"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLAmbisonicsRotationEffectParams =
            IPLAmbisonicsRotationEffectParams(alloc.allocate(IPLAmbisonicsRotationEffectParams.layout))
    }
}
