// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLBakedDataIdentifier(
    public val `$mem`: MemorySegment,
) {
    public var type: IPLBakedDataType
        get() = IPLBakedDataType.fromInt(IPLBakedDataIdentifier.typeHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            IPLBakedDataIdentifier.typeHandle.set(this.`$mem`, 0L, value.value)
        }

    public var variation: IPLBakedDataVariation
        get() = IPLBakedDataVariation.fromInt(
            IPLBakedDataIdentifier.variationHandle.get(
                this.`$mem`,
                0L
            ) as Int
        )
        set(`value`) {
            IPLBakedDataIdentifier.variationHandle.set(this.`$mem`, 0L, value.value)
        }

    public var endpointInfluence: IPLSphere
        get() = IPLSphere(
            IPLBakedDataIdentifier.endpointInfluenceHandle.invokeExact(this.`$mem`, 0L) as
                    MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.endpointInfluence.`$mem`, 0L,
                IPLSphere.layout.byteSize()
            )
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLBakedDataIdentifier.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("type"),
            ValueLayout.JAVA_INT.withName("variation"),
            IPLSphere.layout.withName("endpointInfluence"),
        ).withName("IPLBakedDataIdentifier")

        @JvmField
        public val typeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("type"))

        @JvmField
        public val variationHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("variation"))

        @JvmField
        public val endpointInfluenceHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("endpointInfluence"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLBakedDataIdentifier =
            IPLBakedDataIdentifier(alloc.allocate(IPLBakedDataIdentifier.layout))
    }
}
