// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLBakedDataType(
    public val `value`: Int,
) {
    IPL_BAKEDDATATYPE_REFLECTIONS(0x00000000),
    IPL_BAKEDDATATYPE_PATHING(0x00000001),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLBakedDataType::class.java,
            "fromInt",
            MethodType.methodType(IPLBakedDataType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLBakedDataType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLBakedDataType = when (value) {
            0x00000000 -> IPL_BAKEDDATATYPE_REFLECTIONS
            0x00000001 -> IPL_BAKEDDATATYPE_PATHING
            else -> error("enum not found")
        }
    }
}
