// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLBinauralEffectSettings(
    public val `$mem`: MemorySegment,
) {
    public var hrtf: IPLHRTF
        get() = IPLBinauralEffectSettings.hrtfHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            IPLBinauralEffectSettings.hrtfHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLBinauralEffectSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("hrtf"),
        ).withName("IPLBinauralEffectSettings")

        @JvmField
        public val hrtfHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hrtf"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLBinauralEffectSettings =
            IPLBinauralEffectSettings(alloc.allocate(IPLBinauralEffectSettings.layout))
    }
}
