// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLDirectSimulationFlags(
    public val `value`: Int,
) {
    IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION(0x00000001),
    IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION(0x00000002),
    IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY(0x00000004),
    IPL_DIRECTSIMULATIONFLAGS_OCCLUSION(0x00000008),
    IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION(0x00000010),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLDirectSimulationFlags::class.java,
            "fromInt",
            MethodType.methodType(IPLDirectSimulationFlags::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLDirectSimulationFlags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLDirectSimulationFlags = when (value) {
            0x00000001 -> IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION
            0x00000002 -> IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION
            0x00000004 -> IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY
            0x00000008 -> IPL_DIRECTSIMULATIONFLAGS_OCCLUSION
            0x00000010 -> IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION
            else -> error("enum not found")
        }
    }
}
