// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLHRTFNormType(
    public val `value`: Int,
) {
    IPL_HRTFNORMTYPE_NONE(0x00000000),
    IPL_HRTFNORMTYPE_RMS(0x00000001),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLHRTFNormType::class.java,
            "fromInt",
            MethodType.methodType(IPLHRTFNormType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLHRTFNormType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLHRTFNormType = when (value) {
            0x00000000 -> IPL_HRTFNORMTYPE_NONE
            0x00000001 -> IPL_HRTFNORMTYPE_RMS
            else -> error("enum not found")
        }
    }
}
