// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLHRTFInterpolation(
    public val `value`: Int,
) {
    IPL_HRTFINTERPOLATION_NEAREST(0x00000000),
    IPL_HRTFINTERPOLATION_BILINEAR(0x00000001),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLHRTFInterpolation::class.java,
            "fromInt",
            MethodType.methodType(IPLHRTFInterpolation::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLHRTFInterpolation::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLHRTFInterpolation = when (value) {
            0x00000000 -> IPL_HRTFINTERPOLATION_NEAREST
            0x00000001 -> IPL_HRTFINTERPOLATION_BILINEAR
            else -> error("enum not found")
        }
    }
}
