// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLLogLevel(
    public val `value`: Int,
) {
    IPL_LOGLEVEL_INFO(0x00000000),
    IPL_LOGLEVEL_WARNING(0x00000001),
    IPL_LOGLEVEL_ERROR(0x00000002),
    IPL_LOGLEVEL_DEBUG(0x00000003),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLLogLevel::class.java,
            "fromInt",
            MethodType.methodType(IPLLogLevel::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLLogLevel::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLLogLevel = when (value) {
            0x00000000 -> IPL_LOGLEVEL_INFO
            0x00000001 -> IPL_LOGLEVEL_WARNING
            0x00000002 -> IPL_LOGLEVEL_ERROR
            0x00000003 -> IPL_LOGLEVEL_DEBUG
            else -> error("enum not found")
        }
    }
}
