// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle

@JvmInline
public value class IPLMatrix4x4(
    public val `$mem`: MemorySegment,
) {
    public val elements: NativeArray<NativeArray<IPLfloat32>>
        get() = IPLMatrix4x4.elementsHandle.invokeExact(this.`$mem`, 0L) as MemorySegment

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLMatrix4x4.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4L, MemoryLayout.sequenceLayout(4L, ValueLayout.JAVA_FLOAT))
                .withName("elements"),
        ).withName("IPLMatrix4x4")

        @JvmField
        public val elementsHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("elements"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLMatrix4x4 =
            IPLMatrix4x4(alloc.allocate(IPLMatrix4x4.layout))
    }
}
