// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle

@JvmInline
public value class IPLPanningEffectSettings(
    public val `$mem`: MemorySegment,
) {
    public var speakerLayout: IPLSpeakerLayout
        get() = IPLSpeakerLayout(
            IPLPanningEffectSettings.speakerLayoutHandle.invokeExact(
                this.`$mem`,
                0L
            ) as MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.speakerLayout.`$mem`, 0L,
                IPLSpeakerLayout.layout.byteSize()
            )
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLPanningEffectSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            IPLSpeakerLayout.layout.withName("speakerLayout"),
        ).withName("IPLPanningEffectSettings")

        @JvmField
        public val speakerLayoutHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("speakerLayout"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLPanningEffectSettings =
            IPLPanningEffectSettings(alloc.allocate(IPLPanningEffectSettings.layout))
    }
}
