// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLProbeGenerationType(
    public val `value`: Int,
) {
    IPL_PROBEGENERATIONTYPE_CENTROID(0x00000000),
    IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR(0x00000001),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLProbeGenerationType::class.java,
            "fromInt",
            MethodType.methodType(IPLProbeGenerationType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLProbeGenerationType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLProbeGenerationType = when (value) {
            0x00000000 -> IPL_PROBEGENERATIONTYPE_CENTROID
            0x00000001 -> IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR
            else -> error("enum not found")
        }
    }
}
