// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle

@JvmInline
public value class IPLRay(
    public val `$mem`: MemorySegment,
) {
    public var origin: IPLVector3
        get() = IPLVector3(IPLRay.originHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.origin.`$mem`, 0L, IPLVector3.layout.byteSize())
        }

    public var direction: IPLVector3
        get() = IPLVector3(IPLRay.directionHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.direction.`$mem`, 0L, IPLVector3.layout.byteSize())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLRay.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            IPLVector3.layout.withName("origin"),
            IPLVector3.layout.withName("direction"),
        ).withName("IPLRay")

        @JvmField
        public val originHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("origin"))

        @JvmField
        public val directionHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("direction"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLRay = IPLRay(alloc.allocate(IPLRay.layout))
    }
}
