// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLReflectionsBakeFlags(
    public val `value`: Int,
) {
    IPL_REFLECTIONSBAKEFLAGS_BAKECONVOLUTION(0x00000001),
    IPL_REFLECTIONSBAKEFLAGS_BAKEPARAMETRIC(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLReflectionsBakeFlags::class.java,
            "fromInt",
            MethodType.methodType(IPLReflectionsBakeFlags::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLReflectionsBakeFlags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLReflectionsBakeFlags = when (value) {
            0x00000001 -> IPL_REFLECTIONSBAKEFLAGS_BAKECONVOLUTION
            0x00000002 -> IPL_REFLECTIONSBAKEFLAGS_BAKEPARAMETRIC
            else -> error("enum not found")
        }
    }
}
