// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLReflectionEffectType(
    public val `value`: Int,
) {
    IPL_REFLECTIONEFFECTTYPE_CONVOLUTION(0x00000000),
    IPL_REFLECTIONEFFECTTYPE_PARAMETRIC(0x00000001),
    IPL_REFLECTIONEFFECTTYPE_HYBRID(0x00000002),
    IPL_REFLECTIONEFFECTTYPE_TAN(0x00000003),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLReflectionEffectType::class.java,
            "fromInt",
            MethodType.methodType(IPLReflectionEffectType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLReflectionEffectType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLReflectionEffectType = when (value) {
            0x00000000 -> IPL_REFLECTIONEFFECTTYPE_CONVOLUTION
            0x00000001 -> IPL_REFLECTIONEFFECTTYPE_PARAMETRIC
            0x00000002 -> IPL_REFLECTIONEFFECTTYPE_HYBRID
            0x00000003 -> IPL_REFLECTIONEFFECTTYPE_TAN
            else -> error("enum not found")
        }
    }
}
