// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLSourceSettings(
    public val `$mem`: MemorySegment,
) {
    public var flags: IPLSimulationFlags
        get() = IPLSimulationFlags.fromInt(IPLSourceSettings.flagsHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            IPLSourceSettings.flagsHandle.set(this.`$mem`, 0L, value.value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLSourceSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("flags"),
        ).withName("IPLSourceSettings")

        @JvmField
        public val flagsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("flags"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLSourceSettings =
            IPLSourceSettings(alloc.allocate(IPLSourceSettings.layout))
    }
}
