// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLSIMDLevel(
    public val `value`: Int,
) {
    IPL_SIMDLEVEL_SSE2(0x00000000),
    IPL_SIMDLEVEL_SSE4(0x00000001),
    IPL_SIMDLEVEL_AVX(0x00000002),
    IPL_SIMDLEVEL_AVX2(0x00000003),
    IPL_SIMDLEVEL_AVX512(0x00000004),
    IPL_SIMDLEVEL_NEON(0x00000000),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLSIMDLevel::class.java,
            "fromInt",
            MethodType.methodType(IPLSIMDLevel::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLSIMDLevel::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLSIMDLevel = when (value) {
            0x00000000 -> IPL_SIMDLEVEL_SSE2
            0x00000001 -> IPL_SIMDLEVEL_SSE4
            0x00000002 -> IPL_SIMDLEVEL_AVX
            0x00000003 -> IPL_SIMDLEVEL_AVX2
            0x00000004 -> IPL_SIMDLEVEL_AVX512
            0x00000000 -> IPL_SIMDLEVEL_NEON
            else -> error("enum not found")
        }
    }
}
