// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class IPLSerializedObjectSettings(
    public val `$mem`: MemorySegment,
) {
    public var `data`: Pointer<IPLbyte>
        get() = IPLSerializedObjectSettings.dataHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            IPLSerializedObjectSettings.dataHandle.set(this.`$mem`, 0L, value)
        }

    public var size: IPLsize
        get() = (IPLSerializedObjectSettings.sizeHandle.get(this.`$mem`, 0L) as Long).toULong()
        set(`value`) {
            IPLSerializedObjectSettings.sizeHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLSerializedObjectSettings.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("data"),
            ValueLayout.JAVA_LONG.withName("size"),
        ).withName("IPLSerializedObjectSettings")

        @JvmField
        public val dataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmField
        public val sizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("size"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLSerializedObjectSettings =
            IPLSerializedObjectSettings(alloc.allocate(IPLSerializedObjectSettings.layout))
    }
}
