// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLSpeakerLayoutType(
    public val `value`: Int,
) {
    IPL_SPEAKERLAYOUTTYPE_MONO(0x00000000),
    IPL_SPEAKERLAYOUTTYPE_STEREO(0x00000001),
    IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC(0x00000002),
    IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1(0x00000003),
    IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1(0x00000004),
    IPL_SPEAKERLAYOUTTYPE_CUSTOM(0x00000005),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLSpeakerLayoutType::class.java,
            "fromInt",
            MethodType.methodType(IPLSpeakerLayoutType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLSpeakerLayoutType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLSpeakerLayoutType = when (value) {
            0x00000000 -> IPL_SPEAKERLAYOUTTYPE_MONO
            0x00000001 -> IPL_SPEAKERLAYOUTTYPE_STEREO
            0x00000002 -> IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC
            0x00000003 -> IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1
            0x00000004 -> IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1
            0x00000005 -> IPL_SPEAKERLAYOUTTYPE_CUSTOM
            else -> error("enum not found")
        }
    }
}
