// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLSimulationFlags(
    public val `value`: Int,
) {
    IPL_SIMULATIONFLAGS_DIRECT(0x00000001),
    IPL_SIMULATIONFLAGS_REFLECTIONS(0x00000002),
    IPL_SIMULATIONFLAGS_PATHING(0x00000004),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLSimulationFlags::class.java,
            "fromInt",
            MethodType.methodType(IPLSimulationFlags::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLSimulationFlags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLSimulationFlags = when (value) {
            0x00000001 -> IPL_SIMULATIONFLAGS_DIRECT
            0x00000002 -> IPL_SIMULATIONFLAGS_REFLECTIONS
            0x00000004 -> IPL_SIMULATIONFLAGS_PATHING
            else -> error("enum not found")
        }
    }
}
