// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class IPLSceneType(
    public val `value`: Int,
) {
    IPL_SCENETYPE_DEFAULT(0x00000000),
    IPL_SCENETYPE_EMBREE(0x00000001),
    IPL_SCENETYPE_RADEONRAYS(0x00000002),
    IPL_SCENETYPE_CUSTOM(0x00000003),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            IPLSceneType::class.java,
            "fromInt",
            MethodType.methodType(IPLSceneType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            IPLSceneType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): IPLSceneType = when (value) {
            0x00000000 -> IPL_SCENETYPE_DEFAULT
            0x00000001 -> IPL_SCENETYPE_EMBREE
            0x00000002 -> IPL_SCENETYPE_RADEONRAYS
            0x00000003 -> IPL_SCENETYPE_CUSTOM
            else -> error("enum not found")
        }
    }
}
