// this file is auto generated by endoqa kotlin ffi, modify it with caution
package phonon

import java.lang.foreign.*
import java.lang.invoke.MethodHandle

@JvmInline
public value class IPLTriangle(
    public val `$mem`: MemorySegment,
) {
    public val indices: NativeArray<IPLint32>
        get() = IPLTriangle.indicesHandle.invokeExact(this.`$mem`, 0L) as MemorySegment

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(IPLTriangle.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(3L, ValueLayout.JAVA_INT).withName("indices"),
        ).withName("IPLTriangle")

        @JvmField
        public val indicesHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("indices"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): IPLTriangle =
            IPLTriangle(alloc.allocate(IPLTriangle.layout))
    }
}
